/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package autocomp.UI;

import autocomp.entidades.Disciplina;
import autocomp.entidades.Grupo;
import autocomp.entidades.Usuario;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Importacao;
import logica.Login;
import logica.Questoes;

/**
 *
 * @author adriano
 */
public class ConsQuestaoPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuestaoPanel
     */
    public ConsQuestaoPanel(Grupo g) {
        grupo = g;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AltCorretaGroup = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        Questoes questoes = new Questoes();
        DefaultTableModel model = new DefaultTableModel(
            new Object [][] {
                {questoes.getQuestao(1).getId(),
                    questoes.getQuestao(1).getEnunciado(),
                    questoes.getQuestao(1).getDisciplina().getNome(),
                    questoes.getQuestao(1).getDificuldade()}
            },
            new String [] {
                "Id", "Enunciado", "DIsciplina", "Dificuldade"
            });
            jTable1.setModel(model);
            jTable1.getTableHeader().setReorderingAllowed(false);
            jScrollPane2.setViewportView(jTable1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addContainerGap())
            );
        }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AltCorretaGroup;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    Grupo grupo;
}
