/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package autocomp.UI;

/**
 *
 * @author adriano
 */
public class ImpAlunoPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuestaoPanel
     */
    public ImpAlunoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ArquivoChooser = new javax.swing.JFileChooser();
        ArquivoBox = new javax.swing.JTextField();
        ArquivoLabel = new javax.swing.JLabel();
        ImportarButton = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        ArquivoButton = new javax.swing.JButton();

        ArquivoLabel.setText("Arquivo Selecionado:");

        ImportarButton.setText("Importar");
        ImportarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportarButtonActionPerformed(evt);
            }
        });

        jProgressBar1.setValue(78);

        ArquivoButton.setText("Selecionar Arquivo");
        ArquivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArquivoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ArquivoBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ArquivoLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(ImportarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addGap(115, 115, 115)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ArquivoButton)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(ArquivoButton)
                .addGap(30, 30, 30)
                .addComponent(ArquivoLabel)
                .addGap(18, 18, 18)
                .addComponent(ArquivoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(ImportarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ImportarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportarButtonActionPerformed

    }//GEN-LAST:event_ImportarButtonActionPerformed

    private void ArquivoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArquivoButtonActionPerformed
        ArquivoChooser.showOpenDialog(this);
        ArquivoBox.setText(ArquivoChooser.getCurrentDirectory() + "/" +
                ArquivoChooser.getDescription(ArquivoChooser.getSelectedFile()));
        
    }//GEN-LAST:event_ArquivoButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArquivoBox;
    private javax.swing.JButton ArquivoButton;
    private javax.swing.JFileChooser ArquivoChooser;
    private javax.swing.JLabel ArquivoLabel;
    private javax.swing.JButton ImportarButton;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
