/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package autocomp.UI;

/**
 *
 * @author adriano
 */
public class UsuarioPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuestaoPanel
     */
    public UsuarioPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AltCorretaGroup = new javax.swing.ButtonGroup();
        TiaBox = new javax.swing.JTextField();
        TiaLabel = new javax.swing.JLabel();
        SenhaLabel = new javax.swing.JLabel();
        SenhaBox = new javax.swing.JTextField();
        SalvarButton = new javax.swing.JButton();
        GrupoCombo = new javax.swing.JComboBox();

        TiaLabel.setText("TIA");

        SenhaLabel.setText("Senha");

        SalvarButton.setText("Salvar");

        GrupoCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Professor", "Administrador", "Editor", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TiaLabel)
                            .addComponent(SenhaLabel)
                            .addComponent(TiaBox, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(SenhaBox, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(GrupoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(SalvarButton)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(TiaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TiaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SenhaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SenhaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(GrupoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(SalvarButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AltCorretaGroup;
    private javax.swing.JComboBox GrupoCombo;
    private javax.swing.JButton SalvarButton;
    private javax.swing.JTextField SenhaBox;
    private javax.swing.JLabel SenhaLabel;
    private javax.swing.JTextField TiaBox;
    private javax.swing.JLabel TiaLabel;
    // End of variables declaration//GEN-END:variables
}
