/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package autocomp.UI;

import autocomp.model.Grupo;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import autocomp.controller.AlunoController;
import autocomp.controller.DisciplinaController;

/**
 *
 * @author adriano
 */
public class ImpAlunoPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuestaoPanel
     */
    public ImpAlunoPanel(Grupo g) {
        grupo = g;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ArquivoChooser = new javax.swing.JFileChooser();
        ArquivoBox = new javax.swing.JTextField();
        ArquivoLabel = new javax.swing.JLabel();
        ImportarButton = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        ArquivoButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();

        ArquivoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArquivoBoxActionPerformed(evt);
            }
        });

        ArquivoLabel.setText("Arquivo Selecionado:");

        ImportarButton.setText("Importar");
        ImportarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportarButtonActionPerformed(evt);
            }
        });

        ArquivoButton.setText("Selecionar Arquivo");
        ArquivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArquivoButtonActionPerformed(evt);
            }
        });

        CancelarButton.setText("Cancelar");
        CancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ArquivoBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ArquivoLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ArquivoButton)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelarButton)
                .addGap(31, 31, 31)
                .addComponent(ImportarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(ArquivoButton)
                .addGap(30, 30, 30)
                .addComponent(ArquivoLabel)
                .addGap(18, 18, 18)
                .addComponent(ArquivoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImportarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelarButton))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ImportarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportarButtonActionPerformed
//        boolean b = AlunoController.importar(ArquivoBox.getText());
        for(int i = 0; i < 100; i++){
            jProgressBar1.setValue(i);
        }
//        if(b){
            JOptionPane.showMessageDialog(this, "Listagem de Alunos x Disciplinas \n importada com sucesso", "Sucesso", JOptionPane.DEFAULT_OPTION);                  
            MenuPanel menuPanel = new MenuPanel(grupo);
            JFrame jf = (JFrame) this.getTopLevelAncestor();
            jf.getContentPane().removeAll();
            jf.getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, menuPanel.getPreferredSize().height));
            jf.setMinimumSize(menuPanel.getPreferredSize());
            jf.pack();
//        }
//        else{
            JOptionPane.showMessageDialog(this, "Erro na importacao", "Erro", JOptionPane.ERROR_MESSAGE);                              
//        }
    }//GEN-LAST:event_ImportarButtonActionPerformed

    private void ArquivoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArquivoButtonActionPerformed
        ArquivoChooser.showOpenDialog(this);
        ArquivoBox.setText(ArquivoChooser.getCurrentDirectory() + "/" +
                ArquivoChooser.getDescription(ArquivoChooser.getSelectedFile()));
        
    }//GEN-LAST:event_ArquivoButtonActionPerformed

    private void CancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarButtonActionPerformed
            MenuPanel menuPanel = new MenuPanel(grupo);
            JFrame jf = (JFrame) this.getTopLevelAncestor();
            jf.getContentPane().removeAll();
            jf.getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, menuPanel.getPreferredSize().height));
            jf.setMinimumSize(menuPanel.getPreferredSize());
            jf.pack(); 
    }//GEN-LAST:event_CancelarButtonActionPerformed

    private void ArquivoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArquivoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArquivoBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArquivoBox;
    private javax.swing.JButton ArquivoButton;
    private javax.swing.JFileChooser ArquivoChooser;
    private javax.swing.JLabel ArquivoLabel;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JButton ImportarButton;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    Grupo grupo;
}
