/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package autocomp;

/**
 *
 * @author adriano
 */
public class QuestaoPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuestaoPanel
     */
    public QuestaoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AltCorretaGroup = new javax.swing.ButtonGroup();
        IdBox = new javax.swing.JTextField();
        AltABox = new javax.swing.JTextField();
        AltALabel = new javax.swing.JLabel();
        AltBLabel = new javax.swing.JLabel();
        AltBBox = new javax.swing.JTextField();
        AltCLabel = new javax.swing.JLabel();
        AltCBox = new javax.swing.JTextField();
        AltDLabel = new javax.swing.JLabel();
        AltDBox = new javax.swing.JTextField();
        AltELabel = new javax.swing.JLabel();
        AltEBox = new javax.swing.JTextField();
        AltARadio = new javax.swing.JRadioButton();
        AltBRadio = new javax.swing.JRadioButton();
        AltCRadio = new javax.swing.JRadioButton();
        AltDRadio = new javax.swing.JRadioButton();
        AltERadio = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        EnunciadoPane = new javax.swing.JTextPane();
        QuestaoLabel = new javax.swing.JLabel();
        SalvarButton = new javax.swing.JButton();

        IdBox.setText("1");

        AltALabel.setText("A)");

        AltBLabel.setText("B)");

        AltCLabel.setText("C)");

        AltDLabel.setText("D)");

        AltELabel.setText("E)");

        AltCorretaGroup.add(AltARadio);

        AltCorretaGroup.add(AltBRadio);

        AltCorretaGroup.add(AltCRadio);

        AltCorretaGroup.add(AltDRadio);

        AltCorretaGroup.add(AltERadio);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DISCIPLINA 1", "DISCIPLINA 2" }));
        jComboBox1.setActionCommand("");

        jScrollPane1.setViewportView(EnunciadoPane);

        QuestaoLabel.setText("Questão:");

        SalvarButton.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuestaoLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(AltALabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AltABox, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AltARadio))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(AltBLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AltBBox, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AltBRadio))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(AltDLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AltDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AltDRadio))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(AltCLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AltCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AltCRadio))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(AltELabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AltEBox, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AltERadio))
                                .addComponent(IdBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(SalvarButton)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IdBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(QuestaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AltABox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AltALabel)
                    .addComponent(AltARadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AltBBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AltBLabel))
                    .addComponent(AltBRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AltCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AltCLabel))
                    .addComponent(AltCRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AltDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AltDLabel))
                    .addComponent(AltDRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AltEBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AltELabel))
                    .addComponent(AltERadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(SalvarButton)
                .addGap(31, 31, 31))
        );

        IdBox.setEnabled(false);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AltABox;
    private javax.swing.JLabel AltALabel;
    private javax.swing.JRadioButton AltARadio;
    private javax.swing.JTextField AltBBox;
    private javax.swing.JLabel AltBLabel;
    private javax.swing.JRadioButton AltBRadio;
    private javax.swing.JTextField AltCBox;
    private javax.swing.JLabel AltCLabel;
    private javax.swing.JRadioButton AltCRadio;
    private javax.swing.ButtonGroup AltCorretaGroup;
    private javax.swing.JTextField AltDBox;
    private javax.swing.JLabel AltDLabel;
    private javax.swing.JRadioButton AltDRadio;
    private javax.swing.JTextField AltEBox;
    private javax.swing.JLabel AltELabel;
    private javax.swing.JRadioButton AltERadio;
    private javax.swing.JTextPane EnunciadoPane;
    private javax.swing.JTextField IdBox;
    private javax.swing.JLabel QuestaoLabel;
    private javax.swing.JButton SalvarButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
